version: "2"

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet       # 標準の vet チェック
    - staticcheck # より強力な静的解析
    - errcheck    # エラーハンドリング漏れ
    - unused      # 未使用コード

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/nyahahanoha/BookManagementSystem

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
