[tools]
go = "latest"
pre-commit = "latest"
golangci-lint = "latest"
lefthook = "latest"
yamlfmt = "latest"
pipx = "latest"
yamllint = "latest"
taplo = "latest"
deno = "latest"
buf = "latest"
protoc-gen-go = "latest"
protoc-gen-connect-go = "latest"
grpcurl = "latest"
