FROM golang:1.24 AS builder
WORKDIR /src
COPY . .
RUN go build -o bookMgmtSystem main.go

FROM ubuntu:latest
WORKDIR /app
COPY --from=builder /src/bookMgmtSystem .
COPY ./config.yaml .
RUN chmod +x bookMgmtSystem \
    && apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
EXPOSE 8080
CMD ["/app/bookMgmtSystem"]
