# 実行用イメージ（Alpine や Ubuntuなど軽量）
FROM ubuntu:latest
WORKDIR /app

# ローカルでビルドしたバイナリをコピー
COPY ./bookMgmtSystem .
COPY ./config.yaml .

# 実行権限を付与
RUN chmod +x bookMgmtSystem
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["/app/bookMgmtSystem"]
