# ビルド用
FROM golang:1.24 AS builder
WORKDIR /app

COPY . .
RUN go mod tidy
RUN GOOS=linux GOARCH=arm64 go build -o bookMgmtSystem main.go

# 実行用（Alpine など軽量イメージ）
FROM ubuntu:latest
WORKDIR /app

COPY --from=builder /app/bookMgmtSystem .
RUN chmod +x bookMgmtSystem
RUN apt-get update && apt-get install -y ca-certificates

EXPOSE 8080
# 実行
CMD ["/app/bookMgmtSystem"]
