// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: book_management_system/v1/book.proto

package book_management_systemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBookRequest) Reset() {
	*x = PutBookRequest{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBookRequest) ProtoMessage() {}

func (x *PutBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBookRequest.ProtoReflect.Descriptor instead.
func (*PutBookRequest) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *PutBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

type PutBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBookResponse) Reset() {
	*x = PutBookResponse{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBookResponse) ProtoMessage() {}

func (x *PutBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBookResponse.ProtoReflect.Descriptor instead.
func (*PutBookResponse) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{1}
}

type RenameBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameBookRequest) Reset() {
	*x = RenameBookRequest{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameBookRequest) ProtoMessage() {}

func (x *RenameBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameBookRequest.ProtoReflect.Descriptor instead.
func (*RenameBookRequest) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *RenameBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *RenameBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RenameBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameBookResponse) Reset() {
	*x = RenameBookResponse{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameBookResponse) ProtoMessage() {}

func (x *RenameBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameBookResponse.ProtoReflect.Descriptor instead.
func (*RenameBookResponse) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{3}
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_book_management_system_v1_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_management_system_v1_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_book_management_system_v1_book_proto_rawDescGZIP(), []int{5}
}

var File_book_management_system_v1_book_proto protoreflect.FileDescriptor

const file_book_management_system_v1_book_proto_rawDesc = "" +
	"\n" +
	"$book_management_system/v1/book.proto\x12\x19book_management_system.v1\"$\n" +
	"\x0ePutBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\"\x11\n" +
	"\x0fPutBookResponse\"=\n" +
	"\x11RenameBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x14\n" +
	"\x12RenameBookResponse\"'\n" +
	"\x11DeleteBookRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\"\x14\n" +
	"\x12DeleteBookResponse2\xcf\x02\n" +
	"\x15BookManagementService\x12`\n" +
	"\aPutBook\x12).book_management_system.v1.PutBookRequest\x1a*.book_management_system.v1.PutBookResponse\x12i\n" +
	"\n" +
	"RenameBook\x12,.book_management_system.v1.RenameBookRequest\x1a-.book_management_system.v1.RenameBookResponse\x12i\n" +
	"\n" +
	"DeleteBook\x12,.book_management_system.v1.DeleteBookRequest\x1a-.book_management_system.v1.DeleteBookResponseB\x87\x02\n" +
	"\x1dcom.book_management_system.v1B\tBookProtoP\x01Z^github.com/BookManagementSystem/backend/api/book_management_system/v1;book_management_systemv1\xa2\x02\x03BXX\xaa\x02\x17BookManagementSystem.V1\xca\x02\x17BookManagementSystem\\V1\xe2\x02#BookManagementSystem\\V1\\GPBMetadata\xea\x02\x18BookManagementSystem::V1b\x06proto3"

var (
	file_book_management_system_v1_book_proto_rawDescOnce sync.Once
	file_book_management_system_v1_book_proto_rawDescData []byte
)

func file_book_management_system_v1_book_proto_rawDescGZIP() []byte {
	file_book_management_system_v1_book_proto_rawDescOnce.Do(func() {
		file_book_management_system_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_management_system_v1_book_proto_rawDesc), len(file_book_management_system_v1_book_proto_rawDesc)))
	})
	return file_book_management_system_v1_book_proto_rawDescData
}

var file_book_management_system_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_book_management_system_v1_book_proto_goTypes = []any{
	(*PutBookRequest)(nil),     // 0: book_management_system.v1.PutBookRequest
	(*PutBookResponse)(nil),    // 1: book_management_system.v1.PutBookResponse
	(*RenameBookRequest)(nil),  // 2: book_management_system.v1.RenameBookRequest
	(*RenameBookResponse)(nil), // 3: book_management_system.v1.RenameBookResponse
	(*DeleteBookRequest)(nil),  // 4: book_management_system.v1.DeleteBookRequest
	(*DeleteBookResponse)(nil), // 5: book_management_system.v1.DeleteBookResponse
}
var file_book_management_system_v1_book_proto_depIdxs = []int32{
	0, // 0: book_management_system.v1.BookManagementService.PutBook:input_type -> book_management_system.v1.PutBookRequest
	2, // 1: book_management_system.v1.BookManagementService.RenameBook:input_type -> book_management_system.v1.RenameBookRequest
	4, // 2: book_management_system.v1.BookManagementService.DeleteBook:input_type -> book_management_system.v1.DeleteBookRequest
	1, // 3: book_management_system.v1.BookManagementService.PutBook:output_type -> book_management_system.v1.PutBookResponse
	3, // 4: book_management_system.v1.BookManagementService.RenameBook:output_type -> book_management_system.v1.RenameBookResponse
	5, // 5: book_management_system.v1.BookManagementService.DeleteBook:output_type -> book_management_system.v1.DeleteBookResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_management_system_v1_book_proto_init() }
func file_book_management_system_v1_book_proto_init() {
	if File_book_management_system_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_management_system_v1_book_proto_rawDesc), len(file_book_management_system_v1_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_management_system_v1_book_proto_goTypes,
		DependencyIndexes: file_book_management_system_v1_book_proto_depIdxs,
		MessageInfos:      file_book_management_system_v1_book_proto_msgTypes,
	}.Build()
	File_book_management_system_v1_book_proto = out.File
	file_book_management_system_v1_book_proto_goTypes = nil
	file_book_management_system_v1_book_proto_depIdxs = nil
}
